name: Kubernetes Build & Deploy
on: workflow_dispatch
jobs:
  kubernetes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3ba5ee6fac7e0e30e2ea884e236f282d3a775891
      - uses: medyagh/setup-minikube@35b85ace4fb99111653ecd9f09741138897741e7
      - run: kubectl get pods -A
      - name: Build Image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build . --tag my-app
          echo -n "verifying images:"
          docker images
      - name: Deploy to minikube
        run: |
          kubectl apply -f my-app.yml
      - name: Test Service URI's
        run: |
          minikube service list
          minikube service my-app --url